fos_rest:
  param_fetcher_listener:  true
  serializer:
    serialize_null: true
  view:
    view_response_listener:  true
  exception:
    enabled: true
  body_listener: true
  format_listener:
    rules:
      - { path: '^/api', priorities: [ 'json' ], fallback_format: 'json', prefer_extension: false }
      - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: ~, prefer_extension: true }
